package com.example.medcheckb8.db.enums;

public enum Detachment {
    ALLERGOLOGY,
    ANESTHESIOLOGY,
    VACCINATION,
    GASTROENTEROLOGY,
    GYNECOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    NEUROSURGERY,
    ONCOLOGY,
    ORTHOPEDICS,
    OTORHINOLARYNGOLOGY,
    OPHTHALMOLOGY,
    PROCTOLOGY,
    PSYCHOTHERAPY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    THERAPY,
    UROLOGY,
    PHLEBOLOGY,
    PHYSIOTHERAPY,
    ENDOCRINOLOGY
}
