package com.example.medcheckb8.db.enums;

public enum Position {
    SURGEON,
    CARDIOLOGIST,
    ALLERGOLOGY,
    ANESTHESIOLOGY,
    VACCINATION,
    GASTROENTEROLOGY,
    GYNECOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    NEUROSURGERY,
    ONCOLOGY,
    ORTHOPEDICS,
    OTORHINOLARYNGOLOGY,
    OPHTHALMOLOGY,
    PROCTOLOGY,
    PSYCHOTHERAPY,
    PULMANOLOGY,
    RHEUMATOLOGY,
    THERAPY,
    UROLOGY,
    PHLEBOLOGY,
    PHYSIOTHERAPY,
    ENDOCRINOLOGY

}
